# Generated by Django 5.2.4 on 2025-08-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buy",
            name="card_number",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="buy",
            name="phone_number",
            field=models.CharField(max_length=30),
        ),
    ]
