# Generated by Django 5.2.4 on 2025-08-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_buy_card_number_alter_buy_phone_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Buy",
            new_name="Order",
        ),
    ]
